version: 2
registries:
  maven-repository-repo-dustplanet-de:
    type: maven-repository
    url: https://repo.dustplanet.de
    username: "${{secrets.CI_USER}}"
    password: "${{secrets.CI_PASSWORD}}"

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/API"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/SilkSpawners"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_8_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_8_R3"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_9_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_9_R2"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_10_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_11_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_12_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_13_R2"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_14_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_15_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_16_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_16_R2"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_16_R3"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_17_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_18_R1"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
- package-ecosystem: "maven"
  directory: "/modules/v1_18_R2"
  schedule:
    interval: daily
  registries:
  - maven-repository-repo-dustplanet-de
